Static tables instead of const (#276)
* [ucd] Regenerate with static tables instead of const

Part of https://github.com/harfbuzz/harfrust/issues/275

* [tag_table] Use static instead of const

Part of https://github.com/harfbuzz/harfrust/issues/275

* Change remaining const tables to static

Fixes https://github.com/harfbuzz/harfrust/issues/275

* Revert back some tables to const

error[E0658]: referencing statics in constants is unstable